### ISSUE TITLE
如果是使用tomcat6部署，需要去掉servlet和jsp的依赖

### ISSUE THREAD

**Issue by wangko27** [ameizi/oltu-oauth2-example#1]
在  zetark-oauth2-server 工程的pom文件中 把如下三个依赖加上 <scope>provided</scope>，然后在运行.否则会报一些jsp中错误。
 <dependency>
        <groupId>javax.servlet</groupId>
        <artifactId>javax.servlet-api</artifactId>
        <version>3.0.1</version>
        <scope>provided</scope>
    </dependency>

```
<dependency>
    <groupId>javax.servlet.jsp</groupId>
    <artifactId>jsp-api</artifactId>
    <version>2.2</version>
    <scope>provided</scope>
</dependency>
<dependency>
    <groupId>javax.servlet</groupId>
    <artifactId>jstl</artifactId>
    <version>1.2</version>
    <scope>provided</scope>
</dependency>
```

**Comment by wangko27** [comment]
上面没粘贴完整：
<dependency>
	    <groupId>javax.servlet</groupId>
	    <artifactId>jstl</artifactId>
	    <version>1.2</version>
	    <scope>provided</scope>
	</dependency>

**Comment by sxyx2008** [comment]
楼主细心了。我们的开发和生产环境是tomcat7，故没做tomcat6的测试。谢谢反馈~

**Comment by damn-good** [comment]
I've deployed the war on glassfish server but it is not working fine. I got 404 error on every url...

Still looking for how to fix this. but it works great with the embeded jetty.
