### ISSUE TITLE
关于token过期的事情

### ISSUE THREAD

**Issue by minikiller** [ameizi/oltu-oauth2-example#3]
非常棒的关于oauth2的例子，对我帮助很大，非常感谢你！
有一个问题想请教一下，我看你的例子里面access_token是保存在cache里面，如何控制token的过期呢，好像没看到在哪里有验证啊！

**Comment by ameizi** [comment]
token生成在AccessTokenController中，过期时间设置在OAuthServiceImpl中，token校验在Oauth2Filter中。
