### ISSUE TITLE
授权码code应该只能用一次

### ISSUE THREAD

**Issue by dulinanaaa** [ameizi/oltu-oauth2-example#6]
OAuth2的授权中，code换取token的code，只能使用一次。而现在代码中可以使用若干次
应该改为如下
@Override
    public boolean checkAuthCode(String authCode) {
    	try {
	        String exist = (String) cache.get(authCode).get();
	        if (!StringUtils.isEmpty(exist)) {
	        	cache.put(authCode, null);
	        	// 1
	        	return true;
	        } else {
	        	// 2
	        	return false;
	        }
        }
        catch (Exception e) {
        	// 3
	        return false;
        }
    }
如果非空时，应给清空，1表示成功并要清除code，2表示已清除（失效的code），3表示错误的code（从未生成过的）

**Comment by ameizi** [comment]
是的，这里规则可以根据需要自行拓展优化
